services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  cron:
    image: yvv4docker/task-ef:latest
    container_name: cron-service
    hostname: cron-service
    env_file: .env
    command: /app/cron-job
    networks:
      - app-network
    depends_on:
      - postgres

  api:
    image: yvv4docker/task-ef:latest
    container_name: api-service
    hostname: api-service
    env_file: .env
    command: /app/api
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - postgres
        
      

networks:
  app-network:


volumes:
  postgres_data:
