basePath: /
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Service for analyzing Ethereum transactions and finding addresses with
    maximum balance differences
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ETH Transaction Analysis API
  version: "1.0"
paths:
  /address-eth-diff:
    get:
      consumes:
      - application/json
      description: Returns the Ethereum address with the largest balance change over
        the last N blocks.
      parameters:
      - description: Number of blocks to analyze
        in: query
        name: "n"
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'address: The Ethereum address'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error: Error message'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Find address with maximum balance difference
      tags:
      - analyze
  /health:
    get:
      consumes:
      - application/json
      description: Checks the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Service is unhealthy
          schema:
            type: string
      summary: Health check
      tags:
      - health
schemes:
- http
- https
swagger: "2.0"
